### PR TITLE
Remove username binding

### PR DESCRIPTION
**Pull request by tai271828**
The current Singularity recipe installs all application libraries into a
conda-python virtual environment. The environment is ready to use by activating
it in the right way, and users could run their own driving scripts anywhere
rather than a specific local folder.

Still, please execute `build-solvcon.sh` to verify this commit. Enjoy Solvcon-as-a-Service!

### CODE REVIEW

**Comment by yungyuc** [comment]
Looks good to me.  Merging.

**Comment by yungyuc** [comment]
BTW, is it possible to test the singularity image with Travis-CI?

**Comment by tai271828** [comment]
It is feasible. The question would be more like "what to test" in my opinion. I may leverage the existing `build-solvcon.sh` as a pilot run.

If we want to use Travis-CI of github, the only blocker in my mind is that we need to install singularity. However it should be feasible as well.

Another solution may be use the build result of [Singularity hub](https://singularity-hub.org) directly. I am not sure if slack could integrate Singularity hub. I have to survey it. By the way, this PR is also helpful to host a container image on Singularity hub. I am working on automatic build of Singularity hub for SOLVCON actually. : )

**Comment by yungyuc** [comment]
It will be cool if we can make singularity work on travis-ci.  Slack, however, is less important IMHO.

Regard what to test, I think building solvcon and run unit tests would suffice.

**Pull request merged**
