### PR TITLE
Make the gas probe hook be able to probe norm values of vectors

### PR DESCRIPTION
**Pull request by tai271828**
The original ``solvcon/parcel/gas/probe.py`` could only store scalar values of derived data. If [the returned array of derived data object](https://github.com/solvcon/solvcon/blob/master/solvcon/parcel/gas/probe.py#L68)  is a vector, it will conflict with [the saving action of float64]( https://github.com/solvcon/solvcon/blob/master/solvcon/parcel/gas/probe.py#L153).

The commit https://github.com/solvcon/solvcon/commit/d793e4235f59b7321147c0fb5f353bcebbdc5651 get s the 2-order norm of a vector prior to the saving action. Thus, we could probe the magnitude of velocity for example.

The rest of the commits includes the driving script to probe the magnitude of velocity, and the helper scripts to analyze and visualize the output data over paraview. [This](https://www.dropbox.com/s/ptjv58b78h7xoc8/3d-1d-sod-tube-170508.mp4?dl=0) is an animation example of the driving script output being compared with the result of the 1D Sod tube.

## How to Test This PR

```
$ ./go run
$ ./compare-time-animation.py
```

Then you should get a video file in MP4.

### CODE REVIEW

**Review by yungyuc — APPROVED** [review]

**Comment by yungyuc** [comment]
The code looks good to me except formatting.  I noticed some lines are too long (more than 79 chars).  Could you double-check with the style guide at http://doc.solvcon.net/en/latest/python_style.html ?

P.S. I haven't got ffmpeg installed on osx with conda, so I have to trust you on the movie script.

**Comment by tai271828** [comment]
I have updated this PR and collected all pep8 and coding style fixes in the code and helper scripts as the latest commit. I fixed the original part of the code probe.py to make it meet the pep8 and coding style in the mean time. The logic of the PR does not change at all, and pass the test of "How to Test This PR".

It should be ready to review and merge according to @yungyuc 's comments if approved. Thanks.

**Comment by yungyuc** [comment]
Could you cancel the change to the existing code?  Just change the style of the code you added.

As I quoted at the beginning of the style guide, it's also important to respect the local style:

> BE CONSISTENT.
>
> If you’re editing code, take a few minutes to look at the code around you and determine its style. If they use spaces around all their arithmetic operators, you should too. If their comments have little boxes of hash marks around them, make your comments have little boxes of hash marks around them too.
>
> The point of having style guidelines is to have a common vocabulary of coding so people can concentrate on what you’re saying rather than on how you’re saying it. We present global style rules here so people know the vocabulary, but local style is also important. If code you add to a file looks drastically different from the existing code around it, it throws readers out of their rhythm when they go to read it. Avoid this.

**Comment by tai271828** [comment]
The existing code I changed is probe.py and is for the pep8 only. I changed them because they seem inconsistent with the other existing part of the existing code, say probe.py, and they broke pep8 as well. Would you prefer to fix pep8 in the existing code in another PR?

**Comment by yungyuc** [comment]
Most of the time, we don't change styles for existing code.  Not even in a separate PR / changeset.  Style change always adds noise in bisecting bugs.  But if you really want to modify existing code, yes, do it in a separate PR.

The rule of thumb that I practice, is that if the style of the file you are editing differs from the guide, follow the existing, not the guide.  For new code, first follow the local file, and if you are adding something the local file doesn't have, follow the guide.

**Comment by tai271828** [comment]
Thanks for the comment. I reverted all changeset in the existing code. All pep8/style fixes are now in the new files only, which passed pep8 check. Please review.

**Comment by yungyuc** [comment]
Thanks a lot.  Merged.

**Pull request merged**
