### PR TITLE
Refresh the solely-from-source dependency building system "ground"

### PR DESCRIPTION
**Pull request by yungyuc**
Python is upgraded to 3.6.  Only tested on OSX 10.12 (Sierra).

### CODE REVIEW

**Comment by tai271828** [comment]
Build looks good on Ubuntu 16.04. However, nosetests did not pass.

```
test_dumps (solvcon.tests.test_block.PickleTC) ... Segmentation fault (core dumped)
```

**Comment by yungyuc** [comment]
Do you have the (C/C++) stack trace?

**Comment by tai271828** [comment]
Here is the strace log dumped by ``strace -Ff -tt nosetests solvcon.tests.test_block.PickleTC 2>&1 | tee strace-nosetests_solvcon.tests.test_block.PickleTC.txt``
[strace-nosetests_solvcon.tests.test_block.PickleTC.txt](https://github.com/solvcon/solvcon/files/752930/strace-nosetests_solvcon.tests.test_block.PickleTC.txt)
. It is interesting that the build of Travis CI passed but core dumped on my machine. I will try to build again in a fresh conda environment. If this issue could be reproduced, I will append more debug info against a new issue report.

**Comment by tai271828** [comment]
Build the latest SOLVCON master branch in a fresh conda environment could NOT reproduce https://github.com/solvcon/solvcon/pull/181#issuecomment-277166673 (nosetests passed).

I think the segmentation fault might be caused by some libraries which are not updated in my conda environment, when re-building SOLVCON. Let's stop here, and open an issue if this happends again.

**Comment by yungyuc** [comment]
`strace` shows no information about the call stack.  Run gdb instead.  There was a bug in pybind11 `repr()` that crashed pickler, but I can't tell without the stack trace.  It was fixed before 2.0 release so indeed an outdated library could cause the crash.

**Comment by tai271828** [comment]
The following code block is part of the backtrace of all stack frames, which was dumped by gdb. Generate the core dump by:

* Activate a conda environment prepared by ``solvcon/contrib/conda.sh`` and ``python setup.py build_ext --inplace``
* Fetch the latest SOLVCON trunk.
* Build the aforementioned SOLVCON trunk in the aforementioned conda environment by ``python setup.py build_ext --inplace``
* Run ``nosetests solvcon.tests.test_block.PickleTC``. ( On Ubuntu, we should issue ``ulimit -c unlimited`` first to enable core dump. ) ``Segmentation fault (core dumped)`` should happend.
* ``gdb python -c core`` to access the following code block.

Github does not allow me to upload the whole core fire (~50 MB) for its limitation 10 MB. Please let me know if you want to access the whole core file.



```
(gdb) bt
#0  0x00007faca4b3a551 in type_qualname (type=0x1a61cc8, context=0x0) at Objects/typeobject.c:393
#1  0x00007faca2cc3c68 in save_global (self=0x7fac91ac02a8, obj=0x1a61cc8, name=0x0) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3123
#2  0x00007faca2cc1713 in save (self=0x7fac91ac02a8, obj=0x1a61cc8, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3839
#3  0x00007faca2cc390d in save_reduce (self=0x7fac91ac02a8, args=<optimized out>, obj=0x7faca2681060) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3646
#4  0x00007faca2cc100f in save (self=0x7fac91ac02a8, obj=0x7faca2681060, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3905
#5  0x00007faca2cc2d46 in batch_dict_exact (obj=0x7fac8f56dc48, self=0x7fac91ac02a8) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:2799
#6  save_dict (self=0x7fac91ac02a8, obj=0x7fac8f56dc48) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:2856
#7  0x00007faca2cc1407 in save (self=0x7fac91ac02a8, obj=0x7fac8f56dc48, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3776
#8  0x00007faca2cc3b34 in save_reduce (self=0x7fac91ac02a8, args=<optimized out>, obj=0x7fac8f552978) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3698
#9  0x00007faca2cc100f in save (self=0x7fac91ac02a8, obj=0x7fac8f552978, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3905
#10 0x00007faca2cc5022 in batch_list_exact (obj=0x7fac8f56dbc8, self=0x7fac91ac02a8) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:2544
#11 save_list (self=0x7fac91ac02a8, obj=0x7fac8f56dbc8) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:2594
#12 0x00007faca2cc1452 in save (self=0x7fac91ac02a8, obj=0x7fac8f56dbc8, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3788
#13 0x00007faca2cc2d46 in batch_dict_exact (obj=0x7fac8f56db88, self=0x7fac91ac02a8) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:2799
#14 save_dict (self=0x7fac91ac02a8, obj=0x7fac8f56db88) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:2856
#15 0x00007faca2cc1407 in save (self=0x7fac91ac02a8, obj=0x7fac8f56db88, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3776
#16 0x00007faca2cc3b34 in save_reduce (self=0x7fac91ac02a8, args=<optimized out>, obj=0x7fac8f552710) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3698
#17 0x00007faca2cc100f in save (self=0x7fac91ac02a8, obj=0x7fac8f552710, pers_save=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3905
#18 0x00007faca2cc5787 in dump (obj=0x7fac8f552710, self=0x7fac91ac02a8) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:3937
#19 _pickle_dumps_impl (fix_imports=1, protocol=0x7faca4f29a40 <small_ints+224>, obj=0x7fac8f552710, module=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/_pickle.c:7031
#20 _pickle_dumps (module=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at /home/ilan/minonda/conda-bld/work/Python-3.5.2/Modules/clinic/_pickle.c.h:442
#21 0x00007faca4b25621 in PyCFunction_Call (func=0x7faca341da20, args=0x7fac8f56e0c8, kwds=<optimized out>) at Objects/methodobject.c:98
#22 0x00007faca4bacbd5 in call_function (oparg=<optimized out>, pp_stack=0x7ffce18476f8) at Python/ceval.c:4705
#23 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3236
#24 0x00007faca4bad166 in fast_function (nk=<optimized out>, na=1, n=<optimized out>, pp_stack=0x7ffce1847878, func=0x7fac8f5542f0) at Python/ceval.c:4803
#25 call_function (oparg=<optimized out>, pp_stack=0x7ffce1847878) at Python/ceval.c:4730
#26 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3236
#27 0x00007faca4badb49 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=2, kws=0x7faca5106060, kwcount=0, 
    defs=0x7faca4f9b108, defcount=1, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#28 0x00007faca4badcd8 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, 
    defs=0x7faca4f9b108, defcount=1, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#29 0x00007faca4b03661 in function_call (func=0x7faca4f8a620, arg=0x7fac8f6dc608, kw=0x7fac8f56d688) at Objects/funcobject.c:627
#30 0x00007faca4ad0236 in PyObject_Call (func=0x7faca4f8a620, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2165
#31 0x00007faca4baa234 in ext_do_call (nk=-1888631288, na=1, flags=<optimized out>, pp_stack=0x7ffce1847bc8, func=0x7faca4f8a620) at Python/ceval.c:5034
#32 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3275
#33 0x00007faca4badb49 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=2, kws=0x0, kwcount=0, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#34 0x00007faca4badcd8 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
```

**Comment by tai271828** [comment]
Would you please point out the bug report of pybind11 (or something like that) you were talking about?

**Comment by yungyuc** [comment]
It is very likely that you used an outdated version of pybind11: https://github.com/pybind/pybind11/pull/571

**Pull request merged**
